# OTIMIZACAO COMBINATORIA

# Andrei Pochmann Koenich - Matricula 00308680

# Makefile

# Variaveis de flags de compilacao e de diretorios
FLAGS := -g -fsanitize=address -Wall -o

# Comando para linkar os arquivos compilados e gerar o executavel
link: 
	gcc $(FLAGS) GRASP_MDMT GRASP_MDMT.c

# Comando padrao do Makefile
.DEFAULT_GOAL := link
